name = "my-message-board"
type = "javascript"

account_id = "4817ff23520be0f051961908aa84bd58"
compatibility_date = "2025-09-29"

[functions]
directory = "functions"

[vars]
D1_DATABASE_ID = "172d899b-c9c3-4c86-bbcb-d36a15bac71a"

[bindings]
type = "d1_database"
name = "D1_DATABASE"
database_name = "172d899b-c9c3-4c86-bbcb-d36a15bac71a"
