name = "my-message-board"
type = "javascript"

account_id = "4817ff23520be0f051961908aa84bd58"
compatibility_date = "2025-09-28"

[functions]
directory = "functions"

[vars]
D1_DATABASE_ID = "7da24f38-edd6-43dc-b43c-905d2ed0f4e9"

[bindings]
type = "d1_database"
name = "D1_DATABASE"
database_name = "7da24f38-edd6-43dc-b43c-905d2ed0f4e9"
